# Generated by Django 4.0 on 2022-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_modeluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='username'),
        ),
    ]
