# Generated by Django 5.0.2 on 2024-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="payment_mode",
            field=models.CharField(
                choices=[("FR", "Free"), ("SU", "Subscription"), ("OT", "One Time")],
                default="FR",
                max_length=2,
            ),
        ),
    ]
