# Generated by Django 5.0.2 on 2024-09-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_usersubscription_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertransaction",
            name="reference",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
