# Generated by Django 5.0.2 on 2024-05-13 21:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="extra_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("8c32eb6c-9c5a-427b-a3ac-9fd74e6ee75a"),
                editable=False,
            ),
        ),
    ]
