# Generated by Django 5.0.2 on 2024-05-13 22:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoice",
            "0003_client_user_alter_invoice_status_alter_invoice_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("c71d3f49-9371-4ae7-98d5-61a8aea5bd99"),
                editable=False,
            ),
        ),
    ]
