# Generated by Django 5.0.2 on 2024-05-13 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_invoice_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
