# Generated by Django 5.0.2 on 2024-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_invoiceitems_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitems",
            name="amount",
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
