# Generated by Django 5.0.2 on 2024-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0010_invoicetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitems",
            name="amount",
            field=models.PositiveBigIntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
