# Generated by Django 5.0.2 on 2024-05-14 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_alter_invoiceitems_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
