# Generated by Django 5.0.2 on 2024-05-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_invoicetemplate_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="image",
            field=models.ImageField(default="", upload_to="invoice_temp"),
            preserve_default=False,
        ),
    ]
