# Generated by Django 5.0.2 on 2024-05-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_invoicetemplate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoice.invoicetemplate",
            ),
            preserve_default=False,
        ),
    ]
