# Generated by Django 5.0.2 on 2024-05-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0015_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="mode",
            field=models.CharField(
                choices=[("BT", "Bank Tranfer"), ("CS", "Cash"), ("OT", "Others")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="invoice.payment",
            ),
        ),
    ]
