# Generated by Django 5.0.2 on 2024-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0016_alter_transaction_mode_alter_transaction_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicetemplate",
            name="image",
            field=models.ImageField(null=True, upload_to="invoice_temp"),
        ),
    ]
