# Generated by Django 5.0.2 on 2024-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0018_invoiceitems_created_at_invoiceitems_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_items",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="InvoiceItems",
        ),
    ]
