# Generated by Django 5.0.2 on 2024-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0019_invoice_invoice_items_delete_invoiceitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicetemplate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="invoice_temp"),
        ),
    ]
