# Generated by Django 5.0.2 on 2024-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0020_alter_invoicetemplate_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("draft", "Draft"),
                    ("OVERDUE", "Overdue"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
