# Generated by Django 5.0.2 on 2024-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0021_remove_invoice_status_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
