# Generated by Django 5.0.2 on 2024-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0022_alter_invoice_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
