# Generated by Django 5.0.2 on 2024-09-07 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0029_alter_invoice_issue_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(default="INV", max_length=150)),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("USD", "Usd"),
                            ("NGN", "Ngn"),
                            ("EUR", "Eur"),
                            ("GBP", "Gbp"),
                        ],
                        default="USD",
                        max_length=20,
                    ),
                ),
                ("default_bank", models.CharField(max_length=150)),
                ("account_name", models.CharField(max_length=150)),
                ("account_number", models.CharField(max_length=150)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
