# Generated by Django 5.0.2 on 2024-09-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0032_invoicesettings_due_after"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceMessageCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=150)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="invoice.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
