# Generated by Django 5.0.2 on 2024-10-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0033_invoicemessagecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
