# Generated by Django 5.0.2 on 2024-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0034_widget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicesettings",
            name="account_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="account_number",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="invoicesettings",
            name="default_bank",
            field=models.CharField(default="", max_length=150),
        ),
    ]
