# Generated by Django 5.0.2 on 2024-11-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0036_alter_invoicesettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicetemplate",
            name="custom_image",
            field=models.BinaryField(
                blank=True,
                help_text="Holds the binary data image url of custom templates",
                null=True,
            ),
        ),
    ]
