# Generated by Django 5.0.2 on 2024-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0037_invoicetemplate_custom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
