# Generated by Django 5.0.2 on 2024-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0038_client_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
