# Generated by Django 5.0.2 on 2025-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0039_alter_invoice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
