# Generated by Django 4.0 on 2023-05-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modeluser_username'),
        ('money_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_income',
            new_name='month_income',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='monthly_track',
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_spend', models.IntegerField()),
                ('monthly_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money_tracker.budget')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.modeluser')),
            ],
            options={
                'verbose_name_plural': 'User Categories',
            },
        ),
    ]
