# Generated by Django 4.0 on 2023-05-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modeluser_username'),
        ('money_tracker', '0002_rename_monthly_income_budget_month_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.modeluser'),
        ),
    ]
