# Generated by Django 5.0.2 on 2024-09-29 21:50

import lib.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money_tracker", "0002_alter_monthtrack_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthtrack",
            name="month",
            field=lib.fields.MonthField(),
        ),
        migrations.AddConstraint(
            model_name="monthtrack",
            constraint=models.UniqueConstraint(
                fields=("month", "user"), name="unique_month_user"
            ),
        ),
    ]
